blog/apps/core/urls.py
from django.urls import path
from .views import (
    IndexView,
    post_detail,
    WritePostView,
    AddCommentView,
)


app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('posts/<slug>/', post_detail, name='post_detail'),
    path('write_post/', WritePostView.as_view(), name='write_post'),
    path('add_comment/', AddCommentView.as_view(), name='add_comment'),
]

blog/apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .views import (
    LoginView,
    RegisterView,
    LogoutView,
    ProfileView
)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/core/models.py
from django.db import models
from autoslug import AutoSlugField
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model


class Post(models.Model):
    title = models.CharField(max_length=55, unique=True)

    author_name = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    slug = AutoSlugField(
        populate_from='title',
        unique=True,
        null=True
    )

    image = models.ImageField(upload_to='post_img',
                              blank=True,
                              null=True)

    desc = models.TextField(max_length=255)

    date_of_publ = models.DateTimeField(auto_now_add=True)

    visible = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('core:post_detail', kwargs={'slug': self.slug})

    @property
    def short_desc(self):
        return self.desc[:20] + '...' if len(self.desc) > 20 else self.desc

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    author_name = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    text = models.TextField(max_length=255)

    date_of_publ = models.DateTimeField(auto_now_add=True)

blog/apps/core/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'image', 'desc')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

blog/apps/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse


from .models import Post, Comment
from .forms import PostForm, CommentForm


class IndexView(TemplateView):
    template_name = 'core/index.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_qs = Post.objects.all().order_by('-date_of_publ')
        paginator = Paginator(post_qs, 1)
        page = self.request.GET.get('page')
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)

        context['post_list'] = post_list
        return context


def post_detail(request, slug):
    ctx = {}
    post = Post.objects.get(slug=slug)
    list_comments = post.comment_set.all().order_by('-date_of_publ')
    if post:
        ctx['post'] = post
        ctx['list_comments'] = list_comments
    return render(request, 'core/post_detail.html', ctx)


class WritePostView(FormView):
    template_name = 'core/write_post.html'
    form_class = PostForm
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author_name = self.request.user
        post.save()
        # user.send_user_mail('Registration', 'Welcome!')
        return super().form_valid(form)

    def form_invalid(self, form):
        return JsonResponse(form.errors)


class AddCommentView(FormView):
    template_name = 'core/add_comment.html'
    form_class = CommentForm
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author_name = self.request.user
        # comment.post =
        print(self.request.post)

blog/blog/templates/core/add_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add a comment</title>
</head>
<body>
  <div class="container">
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Add a comment</button>
    </form>
  </div>
</body>
</html>

blog/blog/templates/core/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyBlog</title>
</head>
<body>

{% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'users:profile' %}">ЛК</a>
    <a class="btn btn-primary" href="{% url 'users:logout' %}">Выйти</a>
    <a class="btn btn-primary" href="{% url 'core:write_post' %}">Написать пост</a>

    <h1>Всего постов - {{ post_list|length }}</h1>
    {% for post in post_list %}
        {% if post.visible is True %}
            <a href="{{ post.get_absolute_url }}"><h2>{{ post|title }}</h2><br></a>
            {{ post.short_desc }}

        {% endif %}
    {% endfor %}
{% endif %}

<div>
    {% if post_list.has_previous %}
      <a href="?page={{ post.previous_page_number }}"><</a>
    {% endif %}

    {% for page in post_list.paginator.page_range %}
      {% if page == post_list.number %}
        {{ page }}
      {% else %}
        <a href="?page={{ page }}">{{ page }}</a>
      {% endif %}
    {% endfor %}

    {% if post_list.has_next %}
      <a href="?page={{ post_list.next_page_number }}">></a>
    {% endif %}
</div>

</body>
</html>

blog/blog/templates/core/post_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<a href="{% url 'core:index' %}"><h1>На главную</h1><br></a>
<h2> {{ post.title }} </h2><br>
<img height="300" src="{{ post_img.image.url }}" alt="Vans">
<h3> {{ post.desc }} </h3>
<h3> Date of publication {{ post.date_of_publ }} </h3>
<form class="form-group" action="{% url 'core:add_comment' %}" method="POST">
  {% csrf_token %}
  <div class="text-center mb-4">
  <p class="h3">Add comment</p>
  </div>
  <input type="text" name="text" class="form-control" placeholder="Write your comment here" required>
  <input type="hidden" name="post" value="post" class="form-control">
  <button class="btn btn-primary btn-block" type="submit">Add comment</button>
</form>
<h3>Comments:<br></h3>
{% for comment in list_comments %}
{{ comment.text }}<br>
{{ comment.date_of_publ }}<br><br>
{% endfor %}
</body>
</html>

blog/blog/templates/core/write_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Write a post</title>
</head>
<body>
  <div class="container">
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Add a post</button>
    </form>
  </div>
</body>
</html>