blog/apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .views import (
    LoginView,
    RegisterView,
    LogoutView,
    ProfileView
)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=128, blank=True)
    surname = models.CharField(max_length=128, blank=True)
    email = models.EmailField(max_length=128, unique=True, db_index=True)
    phone = models.CharField(max_length=12, unique=True, db_index=True)
    telegram_id = models.CharField(max_length=25, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = 'custom user'
        verbose_name_plural = 'custom users'

    @property
    def get_full_name(self):
        return f'{self.name.title()} {self.surname.title()}'

    @property
    def get_short_name(self):
        return self.name

    def send_user_mail(self, subject, message):
        send_mail_task.delay(subject, message, self.email)

blog/apps/users/forms.py
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('phone', 'email', 'name', 'surname', 'password1', 'password2')

blog/apps/users/views.py
from django.views.generic import TemplateView, FormView, RedirectView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse_lazy

from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator

from django.http import JsonResponse


class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super().form_valid(form)


class RegisterView(FormView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        user = form.save()
        # user.send_user_mail('Registration', 'Welcome!')
        login(self.request, user)
        return super().form_valid(form)

    def form_invalid(self, form):
        return JsonResponse(form.errors)


class LogoutView(RedirectView):
    pattern_name = 'core:index'

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        return super().get_redirect_url(*args, **kwargs)


class ProfileView(TemplateView):
    template_name = 'users/profile.html'
    login_url = '/users/login/'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = self.request.user.post_set.all().order_by('-date_of_publ')
        post_list_len = post_list.count
        comment_list = None
        context['post_list'] = post_list
        context['post_list_len'] = post_list_len
        return context

blog/blog/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
  <div class="container">
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Войти</button>
    </form>
  </div>
    <a class="btn btn-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
</body>
</html>

blog/blog/templates/users/profile.html
<div class="jumbotron jumbotron-fluid">
<div class="container">
  <h1 class="display-4">{{ user.name }} {{ user.surname }}</h1>
</div>
</div>

<div class="container">

<span class="h3">Your wrote {{ post_list_len }} post(s) </span>
{% for post in post_list %}
  <div>
  Title: <a href="{{ post.get_absolute_url }}"><h3>{{ post|title }}</h3><br></a>
  </div>
{% endfor %}
</div>

blog/blog/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
  <div class="container">
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Зарегистрироваться</button>
    </form>
  </div>
</body>
</html>